/*
TEMPLATE
english
kanji
[
    [kanji, hiragana, english]
]

['','',[['','',''],]],
kurang lebih ini formatnya
['kanji','english',[['kanji1','hiragana1','english1'],['kanji2','hiragana2','english2'],]],

*/
const library_n4 = [
    ['不','not',[['寝不足', 'ねぶそく', 'not']]],
    ['世','world',[['世界', 'せかい', 'world']]],
    ['主','master',[['主義', 'しゅぎ', 'master']]],
    ['事','abstract thing',[['食事', 'しょくじ', 'abstract thing']]],
    ['乗','ride',[['乗り場', 'の\u3000ば', 'ride']]],
    ['京','capital',[['京都', 'きょうと', 'capital']]],
    ['仕','serve',[['仕事', 'しごと', 'serve']]],
    ['代','substitute',[['古代', 'こだい', 'substitute']]],
    ['以','since',[['以上', 'いじょう', 'since']]],
    ['低','low',[['最低', 'さいてい', 'low']]],
    ['作','make',[['手作り', 'てづくり', 'make']]],
    ['体','body',[['体育館', 'たいいくかん', 'body']]],
    ['住','dwell',[['住所', 'じゅうしょ', 'dwell']]],
    ['使','use',[['大使館', 'たいしかん', 'use']]],
    ['便','convenience',[['郵便局', 'ゆうびんきょく', 'convenience']]],
    ['借','borrow',[['貸借', 'たいしゃく', 'borrow']]],
    ['働','work',[['活動', 'かつどう', 'work']]],
    ['元','origin',[['地元', 'じもと', 'origin']]],
    ['兄','older brother',[['兄', 'あに', 'older brother']]],
    ['光','light',[['観光', 'かんこう', 'light']]],
    ['写','copy',[['写真', 'しゃしん', 'copy']]],
    ['冬','winter',[['冬季', 'とうき', 'winter']]],
    ['切','cut',[['大切', 'たいせつ', 'cut']]],
    ['別','separate',[['送別', 'そうべつ', 'separate']]],
    ['力','power',[['電力', 'でんりょく', 'power']]],
    ['勉','diligence',[['勉強', 'べんきょう', 'diligence']]],
    ['動','move',[['自動車', 'じどうしゃ', 'move']]],
    ['区','ward',[['地区', 'ちく', 'ward']]],
    ['医','doctor',[['医師', 'いし', 'doctor']]],
    ['去','leave',[['去年', 'きょねん', 'leave']]],
    ['合','fit',[]],
    ['台','base',[]],
    ['同','same',[]],
    ['味','flavor',[['意味', 'いみ', 'flavor']]],
    ['品','article',[['食品', 'しょくひん', 'article']]],
    ['員','member',[['全員', 'ぜんいん', 'member']]],
    ['問','question',[['質問', 'しつもん', 'question']]],
    ['図','drawing',[['地図', 'ちず', 'drawing']]],
    ['地','ground',[['地球', 'ちきゅう', 'ground']]],
    ['堂','public chamber',[['食堂', 'しょくどう', 'public chamber']]],
    ['場','place',[['場所', 'ばしょ', 'place']]],
    ['声','voice',[]],
    ['売','sell',[]],
    ['夏','summer',[]],
    ['夕','evening',[['夕食', 'ゆうしょく', 'evening']]],
    ['夜','night',[['今夜', 'こんや', 'night']]],
    ['太','fat',[]],
    ['好','like',[['お好み焼き', 'おこのみやき', 'like']]],
    ['妹','younger sister',[]],
    ['姉','older sister',[]],
    ['始','begin',[]],
    ['字','character',[['漢字', 'かんじ', 'character']]],
    ['室','room',[['和室', 'わしつ', 'room']]],
    ['家','house',[]],
    ['寒','cold',[]],
    ['屋','premise',[['居酒屋', 'いざかや', 'premise']]],
    ['工','craft',[['工事', 'こうじ', 'craft']]],
    ['市','city',[]],
    ['帰','return home',[['帰国する', 'きこく', 'return home']]],
    ['広','wide',[['広島', 'ひろしま', 'wide']]],
    ['度','degrees',[]],
    ['建','build',[['建物', 'たてもの', 'build']]],
    ['引','pull',[['引越し', 'ひっこ', 'pull']]],
    ['弟','younger brother',[]],
    ['弱','weak',[]],
    ['強','strong',[]],
    ['待','wait',[]],
    ['心','heart',[]],
    ['思','think',[]],
    ['急','hurry',[['特急', 'とっきゅう', 'hurry']]],
    ['悪','bad',[]],
    ['意','idea',[['意見', 'いけん', 'idea']]],
    ['所','place',[['休憩所', 'きゅうけいじょ', 'place']]],
    ['持','hold',[]],
    ['教','teach',[['教育', 'きょういく', 'teach']]],
    ['文','writing',[['作文', 'さくぶん', 'writing']]],
    ['料','fee',[['料金', 'りょうきん', 'fee']]],
    ['方','direction',[['夕方', 'ゆうがた', 'direction']]],
    ['旅','trip',[['旅行', 'りょこう', 'trip']]],
    ['族','tribe',[['家族', 'かぞく', 'tribe']]],
    ['早','early',[]],
    ['明','bright',[]],
    ['映','reflect',[['映画', 'えいが', 'reflect']]],
    ['春','spring',[['青春', 'せいしゅん', 'spring']]],
    ['昼','daytime',[['昼間', 'ひるま', 'daytime']]],
    ['暑','hot',[]],
    ['暗','dark',[['暗記', 'あんき', 'dark']]],
    ['曜','weekday',[['月曜日', 'げつようび', 'weekday']]],
    ['有','be',[['有名', 'ゆうめい', 'be']]],
    ['服','clothes',[['洋服', 'ようふく', 'clothes']]],
    ['朝','morning',[['朝食', 'ちょうしょく', 'morning']]],
    ['村','village',[['山村', 'さんそん', 'village']]],
    ['林','woods',[]],
    ['森','forest',[]],
    ['業','business',[['営業', 'えいぎょう', 'business']]],
    ['楽','pleasure',[]],
    ['歌','song',[]],
    ['止','stop',[['禁止', 'きんし', 'stop']]],
    ['死','death',[]],
    ['民','people',[]],
    ['池','pond',[]],
    ['注','pour',[['注文', 'ちゅうもん', 'pour']]],
    ['洋','ocean, western',[['洋食', 'ようしょく', 'ocean, western']]],
    ['洗','wash',[['洗濯', 'せんたく', 'wash']]],
    ['海','sea',[['海岸', 'かいがん', 'sea']]],
    ['漢','China',[]],
    ['牛','cow',[['牛肉', 'ぎゅうにく', 'cow']]],
    ['物','thing',[['博物館', 'はくぶつかん', 'thing']]],
    ['特','special',[['特別', 'とくべつ', 'special']]],
    ['犬','dog',[]],
    ['理','reason',[]],
    ['産','give birth',[]],
    ['用','use',[]],
    ['田','rice paddy',[]],
    ['町','town',[]],
    ['画','picture',[['計画', 'けいかく', 'picture']]],
    ['界','world',[]],
    ['病','sick',[['病院', 'びょういん', 'sick']]],
    ['発','departure',[['出発', 'しゅっぱつ', 'departure']]],
    ['県','prefecture',[]],
    ['真','true',[]],
    ['着','wear / arrive',[['到着', 'とうちゃく', 'wear / arrive']]],
    ['知','know',[]],
    ['短','short',[]],
    ['研','sharpen',[]],
    ['私','me',[['私立', 'しりつ', 'me']]],
    ['秋','autumn',[]],
    ['究','research',[]],
    ['答','answer',[['解答欄', 'かいとうらん', 'answer']]],
    ['紙','paper',[['紙袋', 'かみふくろ', 'paper']]],
    ['終','end',[]],
    ['習','learn',[]],
    ['考','think about',[]],
    ['者','someone',[]],
    ['肉','meat',[['豚肉', 'ぶたにく', 'meat']]],
    ['自','oneself',[['自分', 'じぶん', 'oneself']]],
    ['色','color',[]],
    ['英','England',[['英語', 'えいご', 'England']]],
    ['茶','tea',[['茶色', 'ちゃいろ', 'tea']]],
    ['菜','vegetable',[]],
    ['薬','medicine',[]],
    ['親','parent',[['両親', 'りょうしん', 'parent']]],
    ['計','measure',[]],
    ['試','test',[]],
    ['説','theory',[['小説', 'しょうせつ', 'theory']]],
    ['貸','lend',[]],
    ['質','quality',[]],
    ['赤','red',[]],
    ['走','run',[]],
    ['起','wake up',[]],
    ['転','revolve',[]],
    ['軽','light',[]],
    ['近','near',[]],
    ['送','send',[['回送', 'かいそう', 'send']]],
    ['進','advance',[]],
    ['運','carry',[]],
    ['遠','far',[]],
    ['都','metropolis',[]],
    ['重','heavy',[]],
    ['野','field',[]],
    ['銀','silver',[['銀行', 'ぎんこう', 'silver']]],
    ['門','gates',[]],
    ['開','open',[]],
    ['院','institution',[]],
    ['集','collect',[]],
    ['青','blue',[]],
    ['音','sound',[['音節', 'おんせつ', 'sound']]],
    ['頭','head',[]],
    ['題','topic',[]],
    ['顔','face',[]],
    ['風','wind',[['台風', 'たいふう', 'wind']]],
    ['飯','meal',[]],
    ['館','public building',[]],
    ['首','neck',[]],
    ['験','test',[]],
    ['鳥','bird',[['七面鳥', 'しちめんちょう', 'bird']]],
    ['黒','black',[['黒板', 'こくばん', 'black']]],
];
