/*
TEMPLATE
english
kanji
[
    [kanji, hiragana, english]
]

['','',[['','',''],['','',''],['','',''],['','',''],]],
kurang lebih ini formatnya
['kanji','english',[['kanji1','hiragana1','english1'],['kanji2','hiragana2','english2'],['','',''],['','',''],['','',''],]],

INI EXAMPLE NYA
['','',''],
*/
const library_n5 = [
    ['一','one',[['一人', 'ひとり', 'one'],['','',''],['','',''],['','',''],]],
    ['二','two',[['二人', 'ふたり', 'two'],['','',''],['','',''],['','',''],]],
    ['三','three',[['三月', 'さんがつ', 'three'],['','',''],['','',''],['','',''],]],
    ['四','four',[['四季', 'しき', 'four'],['','',''],['','',''],['','',''],]],
    ['五','five',[['五分', 'ごふん', 'five'],['','',''],['','',''],['','',''],]],
    ['六','six',[['六番','ろくばん','number six'],['','',''],['','',''],]],
    ['七','seven',[['七月','しちがつ','month seven'],['','',''],['','',''],]],
    ['八','eight',[['八月','はちがつ','month eight'],['','',''],['','',''],]],
    ['九','nine',[['九月','くがつ','month nine'],['','',''],['','',''],]],
    ['十','ten',[['十月','じゅうがつ','month ten'],['','',''],['','',''],]],
    ['百','hundreds',[['百四年','ひゃくよねん','the 104th year'],['','',''],['','',''],]],
    ['千','thousand',[['','',''],['','',''],['','',''],]],
    ['万','ten thousand; myriad',[['','',''],['','',''],['','',''],]],
    ['父','father',[['お父さん', 'おとうさん', 'father'],['','',''],['','',''],['','',''],]],
    ['母','mother',[['お母さん', 'おかあさん', 'mother'],['','',''],['','',''],['','',''],]],
    ['友','friend',[['友だち', 'ともだち', 'friend'], ['友人', 'ゆうじん', 'friend'],['','',''],['','',''],['','',''],]],
    ['女','womanfemale',[['女性', 'じょせい', 'womanfemale'], ['女の子', 'おんなのこ', 'womanfemale'],['','',''],['','',''],['','',''],]],
    ['男','man; male',[['男性', 'だんせい', 'man; male'], ['男の子', 'おとこのこ', 'man; male'],['','',''],['','',''],['','',''],]],
    ['人','person; person counter suffix',[['日本人', 'にほんじん', 'person; person counter suffix'],['','',''],['','',''],['','',''],]],
    ['子','child',[['子ども', 'こども', 'child'],['','',''],['','',''],['','',''],]],
    ['日','sun; day; day counter suffix',[['日曜日', 'にちようび', 'sun; day; day counter suffix'], ['お日さま', 'おひさま', 'sun; day; day counter suffix'],['','',''],['','',''],['','',''],]],
    ['月','month names; other times; moon; month',[['月曜日', 'げつようび', 'month names; other times; moon; month'], ['お月さま', 'おつきさま', 'month names; other times; moon; month'], ['一ヶ月', 'いっかげつ', 'month names; other times; moon; month'],['','',''],['','',''],['','',''],]],
    ['火','fire; light',[['火曜日', 'かようび', 'fire; light'], ['花火', 'はなび', 'fire; light'],['','',''],['','',''],['','',''],]],
    ['水','water',[['水曜日', 'すいようび', 'water'],['','',''],['','',''],['','',''],]],
    ['木','tree; wood',[['木曜日', 'もくようび', 'tree; wood'],['','',''],['','',''],['','',''],]],
    ['金','goldmetal; money',[['金曜日', 'きんようび', 'goldmetal; money'], ['お金もち', 'おかねもち', 'goldmetal; money'],['','',''],['','',''],['','',''],]],
    ['土','earth; ground; soil',[['土曜日', 'どようび', 'earth; ground; soil'],['','',''],['','',''],['','',''],]],
    ['本','root; book; slender object counter',[['日本', 'にほん', 'root; book; slender object counter'], ['本屋', 'ほんや', 'root; book; slender object counter'],['','',''],['','',''],['','',''],]],
    ['休','rest; vacation',[['休けい', 'きゅうけい', 'rest; vacation'], ['夏休み', 'なつやすみ', 'rest; vacation'],['','',''],['','',''],['','',''],]],
    ['語','word; speech; language; narration; to tell; to speak',[['日本語', 'にほんご', 'word; speech; language; narration; to tell; to speak'], ['英語', 'えいご', 'word; speech; language; narration; to tell; to speak'], ['物語', 'ものがたり', 'word; speech; language; narration; to tell; to speak'],['','',''],['','',''],['','',''],]],
    ['年','yearyear counter',[['一年', 'いちねん', 'yearyear counter'], ['今年', 'ことし', 'yearyear counter'],['','',''],['','',''],['','',''],]],
    ['午','noon',[['正午', 'しょうご', 'noon'],['','',''],['','',''],['','',''],]],
    ['前','before; in front of; previous',[['午前', 'ごぜん', 'before; in front of; previous'],['','',''],['','',''],['','',''],]],
    ['後','behind; after',[['午後', 'ごご', 'behind; after'],['','',''],['','',''],['','',''],]],
    ['時','time; hour counter',[['時間', 'じかん', 'time; hour counter'],['','',''],['','',''],['','',''],]],
    ['間','intervalspaceroomtime',[['三時間', 'さんじかん', 'intervalspaceroomtime'],['','',''],['','',''],['','',''],]],
    ['毎','every',[['毎日', 'まいにち', 'every'],['','',''],['','',''],['','',''],]],
    ['先','previousahead',[['先生', 'せんせい', 'previousahead'],['','',''],['','',''],['','',''],]],
    ['今','nowthe present',[['今日', 'きょうこんにち', 'nowthe present'],['','',''],['','',''],['','',''],]],
    ['何','whathow many',[['何日', 'なんにち', 'whathow many'],['','',''],['','',''],['','',''],]],
    ['上','topabove; to raise; to rise; to go up',[['上手', 'じょおず', 'topabove; to raise; to rise; to go up'],['','',''],['','',''],['','',''],]],
    ['下','bottomunderdown',[['下着', 'したぎ', 'bottomunderdown'],['','',''],['','',''],['','',''],]],
    ['左','left',[['左足', 'ひだりあし', 'left'],['','',''],['','',''],['','',''],]],
    ['右','right',[['右手', 'みぎて', 'right'],['','',''],['','',''],['','',''],]],
    ['北','north',[['北海道', 'ほっかいどう', 'north'],['','',''],['','',''],['','',''],]],
    ['南','south',[['南', 'みなみ', 'south'],['','',''],['','',''],['','',''],]],
    ['東','east',[['東京', 'とうきょう', 'east'],['','',''],['','',''],['','',''],]],
    ['西','west',[['関西', 'かんさい', 'west'],['','',''],['','',''],['','',''],]],
    ['外','outsideforeignother',[['外国人', 'がいこくじん', 'outsideforeignother'],['','',''],['','',''],['','',''],]],
    ['名','namefamefamous; name',[['名前', 'なまえ', 'namefamefamous; name'],['','',''],['','',''],['','',''],]],
    ['高','highcostlytall',[['高校', 'こうこう', 'highcostlytall'],['','',''],['','',''],['','',''],]],
    ['小','smalllittle',[['小学校', 'しょうがっこう', 'smalllittle'],['','',''],['','',''],['','',''],]],
    ['中','middlecenterwithininside',[['中学校', 'ちゅうがっこう', 'middlecenterwithininside'],['','',''],['','',''],['','',''],]],
    ['大','greatbig',[['大学', 'だいがく', 'greatbig'], ['大阪', 'おおさか', 'greatbig'],['','',''],['','',''],['','',''],]],
    ['長','head of an organizationleader; long',[['','',''],['','',''],['','',''],]],
    ['半','half',[['半分', 'はんぶん', 'half'],['','',''],['','',''],['','',''],]],
    ['分','partshare; minute counter; to divideseparate; to understand',[['三分', 'さんぶん', 'partshare; minute counter; to divideseparate; to understand'],['','',''],['','',''],['','',''],]],
    ['学','learningscience; to learn',[['学校', 'がっこう', 'learningscience; to learn'],['','',''],['','',''],['','',''],]],
    ['校','school',[['学校', 'がっこう', 'school'],['','',''],['','',''],['','',''],]],
    ['生','birthlife; to give birth; to live; raw',[['誕生日', 'たんじょうび', 'birthlife; to give birth; to live; raw'],['','',''],['','',''],['','',''],]],
    ['山','mountain',[['富士山', 'ふじさん', 'mountain'],['','',''],['','',''],['','',''],]],
    ['川','riverstream',[['川上', 'かわかみ', 'riverstream'],['','',''],['','',''],['','',''],]],
    ['白','white',[['','',''],['','',''],['','',''],]],
    ['天','heavensky',[['天気', 'てんき', 'heavensky'],['','',''],['','',''],['','',''],]],
    ['雨','rain',[['雨降る夜','あめふるよる','rainy night'],['','',''],['','',''],]],
    ['電','electricityelectric powered',[['電話', 'でんわ', 'electricityelectric powered'], ['電車', 'でんしゃ', 'electricityelectric powered'],['','',''],['','',''],['','',''],]],
    ['気','spiritintentionmindpowerenergy',[['空気', 'くうき', 'spiritintentionmindpowerenergy'],['','',''],['','',''],['','',''],]],
    ['車','wheel; vehicle; car',[['自転車', 'じてんしゃ', 'wheel; vehicle; car'],['','',''],['','',''],['','',''],]],
    ['国','countrynation',[['中国', 'ちゅうごく', 'countrynation'],['','',''],['','',''],['','',''],]],
    ['円','circle; yen (money)',[['百円', 'ひゃくえん', 'circle; yen (money)'],['','',''],['','',''],['','',''],]],
    ['話','talktopicstory; to talk',[['会話', 'かいわ', 'talktopicstory; to talk'],['','',''],['','',''],['','',''],]],
    ['聞','to hearto listento ask',[['新聞', 'しんぶん', 'to hearto listento ask'],['','',''],['','',''],['','',''],]],
    ['食','eatingmealfood',[['食べ物', 'たべもの', 'eatingmealfood'],['','',''],['','',''],['','',''],]],
    ['読','to read',[['読書', 'どくしょ', 'to read'],['','',''],['','',''],['','',''],]],
    ['来','to come',[['未来', 'みらい', 'to come'],['','',''],['','',''],['','',''],]],
    ['書','bookdocument; to write',[['書道', 'しょどう', 'bookdocument; to write'],['','',''],['','',''],['','',''],]],
    ['見','to show',[['','',''],['','',''],['','',''],]],
    ['行','to go',[['旅行', 'りょこう', 'to go'],['','',''],['','',''],['','',''],]],
    ['出','to go outleave',[['出口', 'でぐち', 'to go outleave'],['','',''],['','',''],['','',''],]],
    ['入','enterto go into insert',[['入口', 'いりぐち', 'enterto go into insert'],['','',''],['','',''],['','',''],]],
    ['会','to meet',[['会社', 'かいしゃ', 'to meet'],['','',''],['','',''],['','',''],]],
];